version: '3.0'  # Specify Docker Compose version

services:
  angular:  
    build: webapp  
    container_name: angular
    ports:
      - "4200:4200"
    networks:
      - mean-stack-network  

  express:  
    build: webapp/backend  
    container_name: express
    ports:
      - "9992:9992"  
    environment:
      MONGO_URL: mongodb://admin:raheem12345@database:27017/ems?authSource=admin # Use the authSource for admin database
    networks:
      - mean-stack-network  

  database: # name of the third service 
    image: mongo  
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db/
      - ./mongod.conf:/etc/mongod.conf  # Mount MongoDB configuration
    environment:  # Add root username and password for MongoDB
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: raheem12345
    command: --config /etc/mongod.conf  # Use the config file
    networks:
      - mean-stack-network  

  nginx:  
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount Nginx configuration
    depends_on:
      - angular  
      - express  
    networks:
      - mean-stack-network

volumes:
  mongodb:
    external: true      

networks:
  mean-stack-network:  
    driver: bridge
