version: '3.0'

services:
  angular:
    build: ./webapp # Ensure this points to the directory containing the Dockerfile
    ports:
      - "80:80" # Map container port 80 to VM port 80
    networks:
      - mean-stack-network

  express:
    build: ./webapp/backend # Directory containing Dockerfile for Express
    ports:
      - "9992:9992"
    links:
      - database
    environment:
      MONGO_URL: mongodb://database:27017/ems
    networks:
      - mean-stack-network

  database:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mean-stack-network

networks:
  mean-stack-network:
    driver: bridge